version: '3.8'

services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: api.Dockerfile
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - default

  db:
    container_name: db
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
